translated using typescript page
reactjs/te.react.dev pull request #116
Opened 2024-07-20 01:37 UTC by shajahanshaik915

2024-07-24 21:47 UTC, shajahanshaik915 commented
@srikanth-kandi Could you please review my PR? Thank you!

2024-07-27 11:43 UTC, srikanth-kandi requested changes

2024-07-27 11:43 UTC, srikanth-kandi commented on src/content/learn/typescript.md
> +ఇది children యొక్క విస్తృత నిర్వచనం. రెండవది `React.ReactElement` type ను ఉపయోగించడం, ఇది కేవలం JSX elements మాత్రమే, JavaScript primitives వంటి strings లేదా numbers కాదు:
```suggestion
ఇది చైల్డ్ ఎలిమెంట్ యొక్క బ్రాడ్ డెఫినిషన్. రెండవది `React.ReactElement` టైప్ ను ఉపయోగించడం, ఇది కేవలం JSX ఎలెమెంట్స్ మాత్రమే, JavaScript primitives వంటి strings లేదా numbers కాదు:
```

2024-07-27 11:43 UTC, srikanth-kandi commented on src/content/learn/typescript.md
> +గమనించండి, మీరు TypeScript ను children ఒక నిర్దిష్ట రకం JSX elements అని వివరించడానికి ఉపయోగించలేరు, కాబట్టి కేవలం `<li>` children మాత్రమే అంగీకరించే ఒక కంపోనెంట్ ను type-system ద్వారా వివరించలేరు.
```suggestion
గమనించండి, మీరు TypeScript ను చైల్డ్ ఎలిమెంట్ ఒక నిర్దిష్ట టైప్ JSX ఎలిమెంట్స్ ని వివరించడానికి ఉపయోగించలేరు, కాబట్టి కేవలం `<li>` చైల్డ్ ఎలిమెంట్ మాత్రమే అంగీకరించే ఒక కంపోనెంట్ ను టైప్-సిస్టమ్‌ ద్వారా వివరించలేరు.
```

2024-07-27 11:43 UTC, srikanth-kandi commented on src/content/learn/typescript.md
> +`React.ReactNode` మరియు `React.ReactElement` రెండింటి ఉదాహరణను type-checker తో సహా [ఈ TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wChSB6CxYmAOmX
```suggestion
`React.ReactNode` మరియు `React.ReactElement` రెండింటి ఉదాహరణను టైప్-చెక్కర్ తో సహా [ఈ TypeScript ప్లేగ్రౌండ్](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wChSB6CxYmAOmXRgDkIATJOdNJMGAZzgwAFpxAR+8YADswAVwGkZMJFEzpOjDKw4AFHGEEBvUnDhphwADZsi0gFw0mDWjqQBuUgF9yaCNMlENzgAXjgACjADfkctFnYkfQhDAEpQgD44AB42YAA3dKMo5P46C2tbJGkvLIpcgt9-QLi3AEEwMFCItJDMrPTTbIQ3dKywdIB5aU4kKyQQKpha8drhhIGzLLWODbNs3b3s8YAxKBQAcwXpAThMaGWDvbH0gFloGbmrgQfBzYpd1YjQZbEYARkB6zMwO2SHSAAlZlYIBCdtCRkZpHIrFYahQYQD8UYYFA5EhcfjyGYqHAXnJAsIUHlOOUbHYhMIIHJzsI0Qk4P9SLUBuRqXEXEwAKKfRZcNA8PiCfxWACecAAUgBlAAacFm80W-CU11U6h4TgwUv11yShjgJjMLMqDnN9Dilq+nh8pD8AXgCHdMrCkWisVoAet0R6fXqhWKhjKllZVVxMcavpd4Zg7U6Qaj+2hmdG4zeRF10uu-Aeq0LBfLMEe-V+T2L7zLVu+FBWLdLeq+lc7DYFf39deFVOotMCACNOCh1dq219a+30uC8YWoZsRyuEdjkevR8uvoVMdjyTWt4WiSSydXD4NqZP4AymeZE072ZzuUeZQKheQgA) లో చూడవచ్చు.
```

2024-07-27 11:43 UTC, srikanth-kandi commented on src/content/learn/typescript.md
>  ### Style Props {/*typing-style-props*/}
```suggestion
### స్టైల్ props {/*typing-style-props*/}
```

2024-07-27 11:43 UTC, srikanth-kandi commented on src/content/learn/typescript.md
> +React లో inline styles ఉపయోగిస్తున్నప్పుడు, `style` prop కు పంపబడే object ను వర్ణించడానికి మీరు `React.CSSProperties` ను ఉపయోగించవచ్చు. ఈ type అన్ని సంభావ్య CSS properties యొక్క యూనియన్, మరియు ఇది మీ
```suggestion
React లో ఇన్లైన్ స్టైల్స్ ఉపయోగిస్తున్నప్పుడు, `style` prop కు పంపబడే ఆబ్జెక్ట్ ను డిస్క్రైబ్ చేయడానికి మీరు `React.CSSProperties` ను ఉపయోగించవచ్చు. ఈ టైప్ అన్ని పాసిబుల్ CSS ప్రాపర్టీస్ యొక్క యూనియన్, మరియు ఇది మీరు `style` prop కు సరైన CSS ప్రాపర్టీస్ పంపిస్తున్నారని నిర్ధారించడానికి మరియు మీ ఎడిటర్ లో ఆటో-కంప్లీట్ పొందడానికి మంచి మార్గం.
```

2024-07-27 11:43 UTC, srikanth-kandi commented on src/content/learn/typescript.md
> +## మరింత నేర్చుకోవడానికి {/*further-learning*/}
```suggestion
## మరింత నేర్చుకోవడానికి రిసోర్సెస్ {/*further-learning*/}
```

2024-07-27 11:43 UTC, srikanth-kandi commented on src/content/learn/typescript.md
> +Docs లోని వ్యక్తిగత API పేజీలు TypeScript తో వాటిని ఎలా ఉపయోగించాలో గురించి మరింత లోతైన డాక్యుమెంటేషన్ కలిగి ఉండవచ్చు.
```suggestion
ఈ గైడ్ React తో TypeScript ఉపయోగించడం గురించి బేసిక్స్ ను కవర్ చేసింది, కానీ ఇంకా నేర్చుకోవడానికి చాలా ఉంది.
డాక్స్ లోని ఇండివిడ్యుఅల్ API పేజీలలో TypeScript తో వాటిని ఎలా ఉపయోగించాలి అనే దాని గురించి మరింత ఇన్-డెప్త్ డాక్యుమెంటేషన్ కలిగి ఉండవచ్చు.
```

2024-07-27 11:43 UTC, srikanth-kandi commented on src/content/learn/typescript.md
> +మేము ఈ కింది వనరులను సిఫారసు చేస్తున్నాము:
```suggestion
మేము ఈ కింది రిసోర్సెస్ ను సిఫార్సు చేస్తున్నాము:
```

2024-07-27 11:43 UTC, srikanth-kandi commented on src/content/learn/typescript.md
> + - [The TypeScript handbook](https://www.typescriptlang.org/docs/handbook/) TypeScript కోసం అధికారిక డాక్యుమెంటేషన్, మరియు అధిక భాగం కీలక భాషా లక్షణాలను కవర్ చేస్తుంది.
```suggestion
 - [TypeScript హ్యాండ్‌బుక్](https://www.typescriptlang.org/docs/handbook/) TypeScript కోసం ఆఫిసిఅల్ డాక్యుమెంటేషన్, మరియు అధిక భాగం కీలక లాంగ్వేజ్ ఫీచర్లను కవర్ చేస్తుంది.
```

2024-07-27 11:43 UTC, srikanth-kandi commented on src/content/learn/typescript.md
> + - [The TypeScript release notes](https://devblogs.microsoft.com/typescript/) కొత్త లక్షణాలను లోతుగా కవర్ చేస్తాయి.
```suggestion
 - [TypeScript రిలీజ్ నోట్స్](https://devblogs.microsoft.com/typescript/) కొత్త ఫీచర్లను ఇన్-డెప్త్ గా కవర్ చేస్తాయి.
```

2024-07-27 11:43 UTC, srikanth-kandi commented on src/content/learn/typescript.md
> + - [React TypeScript Cheatsheet](https://react-typescript-cheatsheet.netlify.app/) TypeScript తో React ఉపయోగించడానికి కమ్యూనిటీ-నిర్వహిత చీట్ షీట్, చాలా ఉపయోగకరమైన ఎడ్జ్ కేసులను కవర్ చేస్తూ ఈ డాక్యుమ
```suggestion
 - [React TypeScript చీట్ షీట్](https://react-typescript-cheatsheet.netlify.app/) TypeScript తో React ఉపయోగించడానికి కమ్యూనిటీ-మైన్టైన్డ్ చీట్ షీట్, చాలా ఉపయోగకరమైన ఎడ్జ్ కేసులను కవర్ చేస్తూ ఈ డాక్యుమెంట్ కంటే మరింత విస్తృత తనాన్ని అందిస్తుంది.
```

2024-07-27 11:43 UTC, srikanth-kandi commented on src/content/learn/typescript.md
> + - [TypeScript Community Discord](https://discord.com/invite/typescript) TypeScript మరియు React సమస్యలతో సహాయం కోసం ప్రశ్నలు అడగడానికి మరియు సహాయం పొందడానికి గొప్ప ప్రదేశం.
```suggestion
 - [TypeScript కమ్యూనిటీ Discord](https://discord.com/invite/typescript) TypeScript మరియు React సమస్యలతో సహాయం కోసం ప్రశ్నలు అడగడానికి మరియు సహాయం పొందడానికి గొప్ప ప్రదేశం.
```

2024-08-05 17:26 UTC, srikanth-kandi commented
Thanks @shajahanshaik915 for your contribution. I look forward to seeing more contributions from you 🤝

2024-08-05 17:26 UTC, merged

2024-08-07 19:35 UTC, shajahanshaik915 commented
I'm glad I could contribute, and I look forward to contribute more in the future 🤝.