Translate "Your First Component" to Telugu
reactjs/te.react.dev pull request #134
Opened 2024-12-17 08:41 UTC by Shiva-Sai-ssb

I have translated the `Your First Component` section into Telugu. 
I believe I have completed everything correctly, do let me know if any changes or improvements are required.

Closes #21

2024-12-18 12:31 UTC, Shiva-Sai-ssb commented
Hi @srikanth-kandi, could you please review it when you have a moment?

2024-12-19 02:55 UTC, srikanth-kandi commented
> Hi @srikanth-kandi, could you please review it when you have a moment?

Sure will review, currently I'm bit occupied.

2024-12-22 06:46 UTC, srikanth-kandi requested changes
Thank you @Shiva-Sai-ssb for your contribution!

Please apply the requested changes so I can approve your pull request.

2024-12-22 06:46 UTC, srikanth-kandi commented on src/content/learn/your-first-component.md
> +[React ఆధారిత ఫ్రేమ్‌వర్క్‌లు](/learn/start-a-new-react-project) ఈ దశను మరింత ముందుకు తీసుకుంటాయి. ఒక ఖాళీ HTML ఫైల్‌ను ఉపయోగించి, React "పేజీని నిర్వహించేందుకు" జావాస్క్రిప్ట్‌తో పేజీని నిర్వహించడాన
```suggestion
[React ఆధారిత ఫ్రేమ్‌వర్క్‌లు](/learn/start-a-new-react-project) ఈ దశను మరింత ముందుకు తీసుకెళ్తుంది. ఖాళీ HTML ఫైల్ ఉపయోగించి React‌ తో JavaScript ద్వారా పేజీని "నియంత్రించేందుకు" అవకాశం ఇవ్వడం కంటే బదులు, React కంపోనెంట్ల నుండి HTML‌ ను ఆటోమేటిక్‌గా సృష్టించవచ్చు.  ఇది JavaScript కోడ్ లోడ్ అవ్వడానికి ముందే మీ యాప్ కొన్ని కంటెంట్‌ను ప్రదర్శించేందుకు అనుమతిస్తుంది.
```

2024-12-22 06:46 UTC, srikanth-kandi commented on src/content/learn/your-first-component.md
> +అయితే, అనేక వెబ్‌సైట్లు Reactని కేవలం [మొదలైన HTML పేజీలకు ఇంటరాక్టివిటీ జోడించడానికి](/learn/add-react-to-an-existing-project#using-react-for-a-part-of-your-existing-page) మాత్రమే ఉపయోగిస్తాయి. అవి
```suggestion
అయితే, అనేక వెబ్‌సైట్లు React ని కేవలం [కొన్ని HTML పేజీలకు ఇంటరాక్టివిటీ జోడించడానికి](/learn/add-react-to-an-existing-project#using-react-for-a-part-of-your-existing-page) మాత్రమే ఉపయోగిస్తాయి. అవి పేజీ మొత్తం కోసం ఒకే ఒక రూట్ కాంపొనెంట్ యొక్క స్థానంలో అనేక రూట్ కాంపొనెంట్లను కలిగి ఉంటాయి. మీరు ఎంత React ఉపయోగించాలనుకుంటే అంత లేదా కొంత React ఉపయోగించవచ్చు.
```

2024-12-22 06:46 UTC, srikanth-kandi commented on src/content/learn/your-first-component.md
> +మీరు React ను మొదటి సారి అనుభవించారు! కొన్ని ముఖ్యమైన అంశాలను పునరావలంబం చేద్దాం.
```suggestion
మీరు React యొక్క మొదటి పరిచయాన్ని పొందారు! కొన్ని ముఖ్యమైన పాయింట్లను తిరిగి గుర్తు చేసుకుందాం.
```

2024-12-22 06:46 UTC, srikanth-kandi commented on src/content/learn/your-first-component.md
> +* React మీకు **మీ యాప్ కోసం రీయూజబుల్ UI ఎలిమెంట్స్** అయిన కంపోనెంట్లను సృష్టించడానికి అనుమతిస్తుంది.
```suggestion
* React మీరు **మీ యాప్ కోసం రీయూజబుల్ UI ఎలిమెంట్స్** అయిన కంపోనెంట్లను సృష్టించడానికి అనుమతిస్తుంది.
```

2024-12-22 06:46 UTC, srikanth-kandi commented on src/content/learn/your-first-component.md
> +* React కంపోనెంట్లు సాధారణ జావాస్క్రిప్ట్ ఫంక్షన్లు అయినప్పటికీ:
```suggestion
* React కంపోనెంట్లు సాధారణ JavaScript ఫంక్షన్లు అయినప్పటికీ:
```

2024-12-22 06:46 UTC, srikanth-kandi commented on src/content/learn/your-first-component.md
> +  2. అవి JSX మార్కప్‌ను return ఇస్తాయీ.
```suggestion
  2. అవి JSX మార్కప్‌ను return చేస్తాయి.
```

2024-12-22 06:46 UTC, srikanth-kandi commented on src/content/learn/your-first-component.md
> +ఫంక్షన్ నిర్వచనానికి ముందు `export default` జోడించండి ఇలా:
```suggestion
ఫంక్షన్ డెఫినేషన్ కి ముందు `export default` ని జోడించండి ఇలా:
```

2024-12-22 06:46 UTC, srikanth-kandi commented on src/content/learn/your-first-component.md
> +మీరు ఈ ఉదాహరణను సరిచేయడానికి కేవలం `export` వ్రాయడం ఎందుకు సరిపోదో అనుకుంటున్నారో. `export` మరియు `export default` మధ్య తేడా తెలుసుకోడానికి [కంపోనెంట్లను ఇంపోర్ట్ చేసుకోవడం మరియు ఎక్స్‌పోర్ట్ చేసుకోవ
```suggestion
మీరు ఈ ఉదాహరణను సరిచేయడానికి కేవలం `export` వ్రాయడం ఎందుకు సరిపోదు అని ఆలోచిస్తున్నట్లయితే. `export` మరియు `export default` మధ్య తేడా తెలుసుకోడానికి [కంపోనెంట్లను ఇంపోర్ట్ మరియు ఎక్స్‌పోర్ట్ చేసుకోవడం](/learn/importing-and-exporting-components) గురించి చూడండి.
```

2024-12-22 06:46 UTC, srikanth-kandi commented on src/content/learn/your-first-component.md
> +ఈ `return` స్టేట్‌మెంట్‌లో ఏదో సరైనది లేదు. మీరు దీన్ని సరిచేయగలరా?
```suggestion
ఈ `return` స్టేట్‌మెంట్‌లో ఏదో సరిగ్గా లేదు. మీరు దీన్ని సరిచేయగలరా?
```

2024-12-22 06:46 UTC, srikanth-kandi commented on src/content/learn/your-first-component.md
> +#### రిటర్న్ స్టేట్‌మెంట్‌ని సరిచేయండి {/*fix-the-return-statement*/}
```suggestion
#### return స్టేట్‌మెంట్‌ ని సరిచేయండి {/*fix-the-return-statement*/}
```

2024-12-22 06:46 UTC, srikanth-kandi commented on src/content/learn/your-first-component.md
> +`Profile` కంపోనెంట్ ఎలా ప్రకటించబడిందో మరియు ఉపయోగించబడిందో ఒకసారి పరిశీలించండి. మీరు తప్పు ఎక్కడ ఉంది అన్నదాన్ని గుర్తించగలరా? (React ఎలా కంపోనెంట్లను సాధారణ HTML ట్యాగుల నుండి వేరు చేస్తుందో గుర్తు
```suggestion
`Profile` కంపోనెంట్ ఎలా డిక్లేర్ చేయబడిందో మరియు ఉపయోగించబడిందో ఒకసారి పరిశీలించండి. మీరు తప్పు ఎక్కడ ఉంది అన్నదాన్ని గుర్తించగలరా? (React ఎలా కంపోనెంట్లను సాధారణ HTML ట్యాగుల నుండి వేరు చేస్తుందో గుర్తు తెచ్చుకోండి!)
```

2024-12-22 07:47 UTC, Shiva-Sai-ssb commented
Hey @srikanth-kandi, I've made the changes you requested. Please check!

2024-12-22 08:33 UTC, srikanth-kandi approved these changes

2024-12-22 08:35 UTC, merged