Translate "Importing and Exporting Components" to Telugu
reactjs/te.react.dev pull request #136
Opened 2024-12-23 05:56 UTC by Shiva-Sai-ssb

Closes #36

2024-12-23 07:01 UTC, Shiva-Sai-ssb commented
Hey @srikanth-kandi, I have translated the content into Telugu. 
Please review it when you have the time and let me know if any changes are needed.

2024-12-29 05:37 UTC, srikanth-kandi requested changes
Thank you @Shiva-Sai-ssb for your contribution.

Most of the Translation is good, but need some minor changes.
Please don't blindly translate as it is, just understand the meaning from the statement and convey the same meaning in Telugu with simpler and smaller sentences without losing the context.

2024-12-29 05:37 UTC, srikanth-kandi commented on src/content/learn/importing-and-exporting-components.md
> +డిఫాల్ట్ మరియు నేమ్డ్ ఎక్స్‌పోర్ట్స్ మధ్య గందరగోళాన్ని తగ్గించడానికి, కొంతమంది టీములు ఒకే శైలిని మాత్రమే (డిఫాల్ట్ లేదా నేమ్డ్) ఉపయోగించడం లేదా వాటిని ఒకే ఫైల్‌లో మిళితం చేయడం నుండి తప్పించుకుంటారు.
```suggestion
డిఫాల్ట్ మరియు నేమ్డ్ ఎక్స్‌పోర్ట్స్ మధ్య సంభవించే అయోమయాన్ని తగ్గించడానికి, కొంతమంది టీములు ఒకే స్టైల్ ని (డిఫాల్ట్ లేదా నేమ్డ్) మాత్రమే అనుసరించడానికి లేదా ఒకే ఫైల్లో వాటిని కలపకుండా ఉండటానికి ఎంపిక చేసుకొంటారు. మీకు ఏది సరైనదో అది చేయండి!
```

2024-12-29 05:37 UTC, srikanth-kandi commented on src/content/learn/importing-and-exporting-components.md
> +మొదట, **ఎక్స్‌పోర్ట్** చేయండి `Profile` ని `Gallery.js` నుండి, నేమ్డ్ ఎక్స్‌పోర్ట్ ద్వారా (డిఫాల్ట్ కీవర్డ్‌ను ఉపయోగించకుండా):
```suggestion
మొదట,`Profile` ని `Gallery.js` నుండి **ఎక్స్‌పోర్ట్** చేయండి, నేమ్డ్ ఎక్స్‌పోర్ట్ ద్వారా (డిఫాల్ట్ కీవర్డ్‌ను ఉపయోగించకుండా):
```

2024-12-29 05:37 UTC, srikanth-kandi commented on src/content/learn/importing-and-exporting-components.md
> +తర్వాత, **ఇంపోర్ట్** చేయండి `Profile` ని `Gallery.js` నుండి `App.js` లో, నేమ్డ్ ఇంపోర్ట్ ద్వారా (కర్లీ బ్రేసెస్‌తో):
```suggestion
తర్వాత, `App.js` లో `Profile` ని `Gallery.js` నుండి **ఇంపోర్ట్** చేయండి, నేమ్డ్ ఇంపోర్ట్ ద్వారా (కర్లీ బ్రేసెస్‌తో):
```

2024-12-29 05:37 UTC, srikanth-kandi commented on src/content/learn/importing-and-exporting-components.md
> +చివరగా, **రెండర్** చేయండి `<Profile />` ని `App` కంపోనెంట్ నుండి:
```suggestion
చివరగా, `App` కంపోనెంట్ నుండి `<Profile />` ని **రెండర్** చేయండి:
```

2024-12-29 05:37 UTC, srikanth-kandi commented on src/content/learn/importing-and-exporting-components.md
> +ఇప్పుడు `Gallery.js` లో రెండు ఎక్స్‌పోర్ట్ లు ఉన్నాయి: ఒక డిఫాల్ట్ Gallery ఎక్స్‌పోర్ట్, మరియు ఒక నేమ్డ్ `Profile` ఎక్స్‌పోర్ట్. `App.js` రెండింటినీ ఇంపోర్ట్ చేసుకుంటుంది. ఈ ఉదాహరణలో `<Profile />` ను
```suggestion
ఇప్పుడు `Gallery.js` లో రెండు ఎక్స్‌పోర్ట్లు ఉన్నాయి: ఒక డిఫాల్ట్ `Gallery` ఎక్స్‌పోర్ట్, మరియు ఒక నేమ్డ్ `Profile` ఎక్స్‌పోర్ట్. `App.js` రెండింటినీ ఇంపోర్ట్ చేసుకుంటుంది. ఈ ఉదాహరణలో `<Profile />` ను `<Gallery />` గా ఎడిట్ చేసి, మళ్ళీ వెనక్కి మార్చడానికి ప్రయత్నించండి:
```

2024-12-29 05:37 UTC, srikanth-kandi commented on src/content/learn/importing-and-exporting-components.md
> +మీరు ఎక్కడ పిలవబడతాయో అక్కడ మీ కంపోనెంట్లను ఇంపోర్ట్ చేయడం మర్చిపోకండి. `Gallery` కూడా `Profile` ను ఉపయోగించదేమో?
```suggestion
మీ కంపోనెంట్లను అవి పిలవబడే చోట ఇంపోర్ట్ చేయడం మర్చిపోవద్దు. `Gallery` కూడా `Profile`ను ఉపయోగిస్తుంది కదా?
```

2024-12-29 05:37 UTC, srikanth-kandi commented on src/content/learn/importing-and-exporting-components.md
> +మీరు ఒక రకమైన ఎక్స్‌పోర్ట్స్‌తో పని చేయగానే, ఇతర రకమైన ఎక్స్‌పోర్ట్స్‌తో కూడా పనిచేయాలని ప్రయత్నించండి.
```suggestion
మీరు ఒక రకమైన ఎక్స్‌పోర్ట్‌లతో అది పని చేసేలా చేసిన తరువాత, మరొక రకంతో కూడా పని చేసేలా ప్రయత్నించండి.
```

2024-12-29 05:37 UTC, srikanth-kandi commented on src/content/learn/importing-and-exporting-components.md
> +ఇది నేమ్డ్ ఎక్స్‌పోర్ట్స్‌తో సమాధానం:
```suggestion
ఇది నేమ్డ్ ఎక్స్‌పోర్ట్‌లతో పరిష్కారం:
```

2024-12-29 05:37 UTC, srikanth-kandi commented on src/content/learn/importing-and-exporting-components.md
> +ఇది డిఫాల్ట్ ఎక్స్‌పోర్ట్స్‌తో సమాధానం:
```suggestion
ఇది డిఫాల్ట్ ఎక్స్‌పోర్ట్‌లతో పరిష్కారం:
```

2024-12-29 07:22 UTC, Shiva-Sai-ssb commented
Hi @srikanth-kandi, I've made the changes as per your suggestions and would appreciate a re-review.

> Please don't blindly translate as it is, just understand the meaning from the statement and convey the same meaning in Telugu with simpler and smaller sentences without losing the context.

Definitely, I will keep that in mind and try to translate into simpler sentences.

2024-12-29 10:52 UTC, srikanth-kandi approved these changes

2024-12-29 10:52 UTC, merged