translated Intro section of tutorial: tic tac toe page to telugu
reactjs/te.react.dev pull request #3
Opened 2023-05-18 17:33 UTC by gsteja2307

#2

2023-05-18 17:34 UTC, gsteja2307 commented
under progress

2023-05-29 06:59 UTC, g-savitha requested changes
Please add `package-lock.json` to `.gitignore`. Don't push it.

2023-07-16 10:05 UTC, gsteja2307 commented
By committing the package-lock.json file, we are ensuring that all developers working on the project have the same dependencies and versions installed

we shouldn't add it to gitignore

2023-07-17 02:43 UTC, g-savitha commented
Can you make the changes today? @gsteja2307

2024-01-13 13:36 UTC, g-savitha approved these changes

2024-01-13 13:36 UTC, merged