Add React to an Existing Project page translated to Telugu
reactjs/te.react.dev pull request #80
Opened 2024-01-17 11:16 UTC by srikanth-kandi

Hello @g-savitha, @gsteja2307 and @vamsikrishnareddybevara

I have translated the entire page of [Add React to an Existing Project](https://te-react-dev.vercel.app/learn/add-react-to-an-existing-project) to Telugu by following the [Telugu Glossary](https://github.com/reactjs/te.react.dev/issues/13) and other guidelines provided.

Please carefully review the translated content, and merge it ASAP because I'm eager to translate other pages also but as mentioned in #1 "**Please take only one page at a time**".

Merging this PR will close #10

Thank you :)

2024-01-18 09:04 UTC, srikanth-kandi commented
Please add me as one of the maintainers, I have experience with React and have completed many projects using it.
Check them on my profile @srikanth-kandi and my certifications mentioned in [LinkedIn](https://www.linkedin.com/in/srikanthkandi/details/certifications/)

@g-savitha @gsteja2307

According to the guidelines about **Adding a Maintainer** mentioned in [translations.react.dev](https://github.com/reactjs/translations.react.dev?tab=readme-ov-file#adding-a-maintainer), if any of the maintainers like @vamsikrishnareddybevara isn't active on this repository for the last 3 months or so. They need to be replaced by others.

So I hope you consider adding me as another maintainer for this repository.

2024-01-19 09:00 UTC, srikanth-kandi commented
Hello @g-savitha please review this pull request, as I'm also working on another [page](https://github.com/reactjs/te.react.dev/issues/9), so if PR was merged I can send another pull request of that translated page.

2024-01-19 17:53 UTC, gsteja2307 commented on src/content/learn/add-react-to-an-existing-project.md
> +**మీరు React ను లోకల్ గా వాడాలి అనుకొంటే [Node.js](https://nodejs.org/en/) ను ఇన్స్టాల్ చేసుకోవాలి.** మీరు [ఆన్‌లైన్‌](/learn/installation#try-react) ద్వారానైనా లేదా సాధారణ HTML పేజీతో ప్రయత్నించవచ్చ
మీరు React ను లోకల్ గా వాడాలి అనుకొంటే [Node.js](https://nodejs.org/en/) ను ఇన్స్టాల్ చేసుకోవలసి ఉంటుంది లేదా ** మీరు [React ను ఆన్‌లైన్‌లో ప్రయత్నించండి ](/learn/installation#try-react) లేదా సాధారణ HTML పేజీతో ప్రయత్నించవచ్చు,   కానీ వాస్తవానికి మీరు ప్రాజెక్ట్ డెవలప్మెంట్కు  వాడాలనుకునే  JavaScript టూలింగ్ కు Node.js అవసరం

2024-01-19 17:53 UTC, gsteja2307 commented on src/content/learn/add-react-to-an-existing-project.md
> +మీరు ఇప్పటికే ఉన్న మీ ప్రాజెక్ట్‌కి కొంత ఇంటరాక్టివిటీని జోడించాలనుకుంటే, మీరు దాన్ని React లో తిరిగి వ్రాయవలసిన అవసరం లేదు. ఇప్పటికే ఉన్న మీ స్టాక్‌కి React ని జోడించండి మరియు ఇంటరాక్టివ్ React కాంప
మీరు ఇప్పటికే ఉన్న మీ ప్రాజెక్ట్‌కి కొంత ఇంటరాక్టివిటీని జోడించాలనుకుంటే, దాన్ని React లో మళ్ళీ రాసే అవసరం లేకుండా, మీ ఉన్న స్టాక్‌లో React ను జోడించి. ఇంటరాక్టివ్ React కాంపోనెంట్లను మీరు ఎక్కడైనా రెండర్ చేయవచ్చు.

2024-01-19 17:55 UTC, gsteja2307 commented
thanks for your effort on translating the project to Telugu. I noticed some sentences seem to be directly translated, which may not align with the contextual meaning in Telugu. Could you please review the translation for grammatical accuracy and context sensitivity? It's important that the translated content maintains the original message and flows naturally in Telugu. A thorough proofreading would be greatly appreciated. Thanks!

> Hello @g-savitha, @gsteja2307 and @vamsikrishnareddybevara
> 
> I have translated the entire page of [Add React to an Existing Project](https://te-react-dev.vercel.app/learn/add-react-to-an-existing-project) to Telugu by following the [Telugu Glossary](https://github.com/reactjs/te.react.dev/issues/13) and other guidelines provided.
> 
> Please carefully review the translated content, and merge it ASAP because I'm eager to translate other pages also but as mentioned in #1 "**Please take only one page at a time**".
> 
> Merging this PR will close #10
> 
> Thank you :)

Appreciate your work on the Telugu translation of this page. I've noticed certain phrases seem directly translated, potentially losing the intended meaning in Telugu. Please recheck for grammatical and contextual accuracy. Ensuring that the translation accurately conveys the original message and reads naturally in Telugu is crucial. 

Detailed proofreading would be very helpful. Thanks!

I've provided some examples in the PR review. Please ensure a comprehensive check before finalizing your changes. Additionally, be cautious with text in square brackets, typically links, to preserve context. If feasible, also update the linked titles for clarity and relevance.

2024-01-21 12:11 UTC, g-savitha reviewed
Comments need not to be updated, as these will not be shown to end user.

2024-01-21 13:04 UTC, g-savitha requested changes

2024-01-21 13:04 UTC, g-savitha commented on src/content/learn/add-react-to-an-existing-project.md
> +మీరు ఇప్పటికే ఉన్న ప్రాజెక్ట్‌లో React ని స్వీకరించినప్పుడు, చిన్న ఇంటరాక్టివ్ కాంపోనెంట్‌లతో (ఉదాహరణకు బటన్లు) ప్రారంభించడం సాధారణం, ఆపై మీ పేజీ మొత్తం React తో నిర్మించబడే వరకు క్రమంగా “పైకి కదులుత
మీ పేజీ మొత్తం React తో నిర్మించబడే వరకు క్రమంగా “పైకి Veluthu undandi"

2024-01-21 14:15 UTC, srikanth-kandi commented
> Comments need not to be updated, as these will not be shown to end user.

But as mentioned in this [style-guide](https://github.com/reactjs/translations.react.dev/blob/main/style-guide.md#text-in-code-blocks) **Leave text in code blocks untranslated except for comments**

So if we translate the comments of code blocks to Telugu it can help easily understand the purpose of that code block for a newbie.

@g-savitha

2024-01-21 17:43 UTC, srikanth-kandi commented on src/content/learn/add-react-to-an-existing-project.md
> +మీ యాప్‌లోని React భాగం ఆ ఫ్రేమ్‌వర్క్‌లలో రూపొందించబడిన [ఉత్తమ అభ్యాసాల నుండి ప్రయోజనం పొందగలదని](/learn/start-a-new-react-project#can-i-use-react-without-a-framework) ఇది నిర్ధారిస్తుంది.
please suggest the easy sentence, i didn't get one

2024-01-24 08:13 UTC, srikanth-kandi commented
Can anyone review this PR

@g-savitha @gsteja2307

2024-01-27 14:40 UTC, srikanth-kandi commented
> Please add me as one of the maintainers, I have experience with React and have completed many projects using it. Check them on my profile @srikanth-kandi and my certifications mentioned in [LinkedIn](https://www.linkedin.com/in/srikanthkandi/details/certifications/)
> 
> @g-savitha @gsteja2307
> 
> According to the guidelines about **Adding a Maintainer** mentioned in [translations.react.dev](https://github.com/reactjs/translations.react.dev?tab=readme-ov-file#adding-a-maintainer), if any of the maintainers like @vamsikrishnareddybevara isn't active on this repository for the last 3 months or so. They need to be replaced by others.
> 
> So I hope you consider adding me as another maintainer for this repository.

You guys didn't consider making me a maintainer, and you are also not responding to the contributions.
Consider responding to this repository updates by sparing at least some time a day 🙏

@g-savitha @gsteja2307

2024-03-02 13:23 UTC, srikanth-kandi commented
Hey @g-savitha and @gsteja2307 

Please review this and my existing pull requests, I requested you make me a maintainer on #1. Otherwise, add some other maintainers you know who will actively monitor the contributions on this repository.

Waiting for your response.

2024-03-25 15:28 UTC, merged